language: r
r:
  - oldrel
  - release
  - devel

before_install:
  - tlmgr install numprint
  
cache: packages

warnings_are_errors: true

notifications:
  email:
    on_success: change
    on_failure: change

repos:
  CRAN: https://cloud.r-project.org
